<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kavinschool.api</groupId>
        <artifactId>api-dev-companion</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>day2-labs</artifactId>
    <packaging>pom</packaging>
    <name>Day 2 Labs</name>

    <modules>
        <module>lab1_2_writing_an_openapi_specification</module>
        <module>lab1_3_peer_review_and_interactive_docs</module>
    </modules>
</project>
